name: Cleanup Old Workflow Runs

on:
  schedule:
    # Berjalan setiap hari pada jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Memungkinkan pemicu manual dari tab Actions

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
          delete_run_by_conclusion_pattern: "success, failure, cancelled, skipped"
